### ISSUE TITLE
Interaction with cURL plugin

### ISSUE THREAD

**Issue by Yulien37** [miyako/4d-plugin-qrencode#1]
On Windows 7 64 bits, 4D v15.2, if 4d-plugin-qrencode AND 4d-plugin-curl are in the plugin folders, 4D crashes when calling QRCode method.
(You can try with Method1 provided in the example database)

Here are the crash informations :
 Signature du problème :
  Nom d’événement de problème: APPCRASH
  Nom de l’application:   4D.exe
  Version de l’application:   15.0.2.0
  Horodatage de l’application:    56ff37db
  Nom du module par défaut:    libpng16-16.dll
  Version du module par défaut:    0.0.0.0
  Horodateur du module par défaut: 54cae64e
  Code de l’exception:    c0000005
  Décalage de l’exception:   0001e3cb
  Version du système:  6.1.7601.2.1.0.256.1
  Identificateur de paramètres régionaux: 1036
  Information supplémentaire n° 1:   e65e
  Information supplémentaire n° 2:   e65ebb112b10d942453062e6f5ff1c91
  Information supplémentaire n° 3:   b831
  Information supplémentaire n° 4:   b831433e6e6b39ff6f5527d2f6c4ef17

**Comment by miyako** [comment]
I guess it is a conflict of different DLLs using the same name (ZLIB1)
one is using an MSVC DLL, the other is using a MinGW DLL.

you could probably remove the ZLIB inside QRENCODE.

**Comment by Yulien37** [comment]
Tried to remove ZLIB from QRENCODE, it doesn't work, 4D is still crashing.

**Comment by miyako** [comment]
I've embedded ZLIB and LIBPNG, could you try again, please?

**Comment by Yulien37** [comment]
It works.
Thanks a lot.
