### ISSUE TITLE
contribution for additional features

### ISSUE THREAD

**Issue by relume** [miyako/4d-plugin-qrencode#2]
Hello

Thank you very much for publishing this 4D-plugin - I appreciate this very much.

I would like to ask if I can contribute to further development to this plugin. Especially I would like to purpose following additional features:

- possibility to pass as parameter a minimal QR-code version : e.g. a minimal version parameter of 10 would generate a QR-code that has minimal version of 10 but if the payload is bigger that version 10 capacity the appropriate version to hold the payload is automatically chosen in dependence of the error-correction level.
- possibility that the QR-code generator function returns in an output-parameter the automatically chosen version depending on payload length and error-correction level.
- possibility to define by the mode-parameter also default QR-code generation modes as "numeric", alphanumeric, binary. Especially the binary modus would be very appreciated.

Many thanks in advance and best regards, 

relume

**Comment by miyako** [comment]
Hello, how do you like to implement those features?
You have a few options: 

- Fork the project

- Push code changes to the project

- Suggestions only and expect me to implement them

**Comment by relume** [comment]
Hello

As I am bound to 4D v11, forking the project is not the best choice I guess. Pushing code changes are possible, although I would like not to interfere to much to your clean code in respect and features additions are gradual. What are your preferences?

**Comment by miyako** [comment]
Hello, thank you for sharing your thoughts. Right now, I am not at liberty to invest time in a v11 project, unless it is a formal contract work for a customer. Sorry for that...
